name = "cf-workers-status-page-staging"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/10 * * * *"]

[site]
bucket = "out"
entry-point = "./"

[placement]
mode = "smart"

# uncomment and adjust following if you are not using GitHub Actions
[env.production]
kv_namespaces = [{binding="KV_STATUS_PAGE", id="c86b2bcd5e59442a8628ea64a4fcbc11"}]
